### ISSUE TITLE
Sync'd to currect Octoprint devel

### ISSUE THREAD

**Issue by ymilord** [PxT/OctoPrint#7]
Is there any chance of getting this sync'd up with the current devel of OctoPrint?

**Comment by PxT** [comment]
Sorry but it's probably not very likely.  I'm not spending any time on this currently.  If you are able to try it I'll gladly merge a pull request.

**Comment by ymilord** [comment]
Unfortunately my foo is weak in this department. I've tried to manually apply the changes to the current devel but then OctoPrint crashes and locks up the RPi. So I am obviously doing something wrong.
